version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: my_postgres
        restart: always
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: laravel_password
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mongo:
        image: mongo:latest
        container_name: my_mongo
        restart: always

    redis:
        image: redis:latest
        container_name: my_redis
        restart: always

    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my_laravel_app
        restart: always
        depends_on:
            - postgres
            - mongo
            - redis
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www

volumes:
    postgres_data:

