version: '3.8'
services:
    # Laravel service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        networks:
            - laravel

    # Postgres service
    db:
        image: postgres:15.3
        container_name: db
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_PASSWORD: your_postgres_password
        networks:
            - laravel

    # Redis service
    redis:
        image: redis:6.2
        container_name: redis
        restart: unless-stopped
        tty: true
        command: ["redis-server", "--requirepass your_redis_password"]
        networks:
            - laravel

    # MongoDB service
    mongo:
        image: mongo:4.4
        container_name: mongo
        restart: unless-stopped
        tty: true
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: your_mongo_password
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
